name: Build package, documentation and test coverage

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build with Maven
        run: mvn package
      - name: Upload the build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build-artifact
          path: target/
      - name: Upload the documentation artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: documentation-artifact
          path: target/apidocs/
      - name: Upload the test coverage artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: test-coverage-artifact
          path: target/site/jacoco/
