name: Test Java project on different OS

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build with Maven on ${{ matrix.os }}
        run: mvn package
